<a href="https://colab.research.google.com/github/josevalladares99/datawarehouse-seguros/blob/main/Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/josevalladares99/datawarehouse-seguros.git

In [1]:
import pandas as pd

In [14]:
url = "https://raw.githubusercontent.com/josevalladares99/datawarehouse-seguros/main/data/clientes.csv"

In [16]:
df = pd.read_csv(url)
print("Dataset cargado correctamente")

Dataset cargado correctamente

In [17]:
display(df.head())

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

BLOQUE 2: Exploración del DATASET

In [18]:
print("Primeras filas del DATASET")
display(df.head())

Primeras filas del DATASET

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [19]:
print("Dimensiones del dataset (filas, columnas)")
print(df.shape)

Dimensiones del dataset (filas, columnas)
(3030, 7)

In [20]:
print("Columnas del dataset")
print(df.columns)

Columnas del dataset
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [21]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
dtype: object

In [22]:
print("Valores nulos por columnas")
print(df.isnull().sum())

Valores nulos por columnas
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [23]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

BLOQUE 3: LIMPIEZA DE DATOS

In [24]:
#Eliminar espacios al inicio y al final en columnas de texto
for col in df.select_dtypes(include="object").columns:df[col].str.strip()

In [26]:
#Normalizar el nombre
df["nombre"]=df["nombre"].str.title()

In [27]:
#Normalizar el email
df["email"]=df["email"].str.lower()

In [28]:
#Normalizar el genero
df["genero"]=df["genero"].str.upper()

In [30]:
#Convertir fecha de nacimiento a formato fecha
df['fecha_nacimiento']=pd.to_datetime(df['fecha_nacimiento'],errors="coerce")

In [31]:
#Normalizar ciudad
df["ciudad"]=df["ciudad"].str.title()

In [32]:
#Limpieza de segmento
df['segmento']=df['segmento'].astype(str)
df['segmento']=df['segmento'].str.strip()
df['segmento']=df['segmento'].str.upper()

BLOQUE 4: VALIDACIÓN DE DATOS

In [35]:
#Crear columna para registrar errores
df["motivo_rechazo"]=""

#Validar id_cliente
df.loc[df["id_cliente"].isnull(),"motivo rechazo"] +="id_cliente nulo; "

KeyError: 'motivo rechazo'